from app.models.channel import Channel
from app.models.user import User
from app.models.loan import Loan
from app.models.loan_installment import LoanInstallment
from app.models.loan_transaction import LoanTransaction
from app.models.admin import Admin
from app.models.risk_report import RiskControlReport
from app.models.risk_composite_report import RiskCompositeReport
from app.models.blacklist import BlacklistEntry
from app.models.phone_binding import UserPhoneBinding
from app.models.user_event import UserEvent
from app.models.ops_history import AdminLoginHistory, ConfigChangeHistory, MessageTemplate
from app.models.product import Product
from app.models.ecard_pool import EcardPool
from app.models.loan_ecard import LoanEcard
from app.models.oauth_client import OAuthClient
from app.models.oauth_token import OAuthToken
from app.models.overdue_fee_config import OverdueFeeConfig
from app.models.purchase_contract import PurchaseContractSignature
from app.models.loan_mandate import LoanMandate
from app.models.momo_transaction import MomoTransaction
from app.models.compliance_rule import ComplianceRule
