import request from './request';

// Admin API
export const login = (data) => request.post('/admin/login', data);
export const getAdminInfo = () => request.get('/admin/me');
export const changeAdminPassword = (data) => request.post('/admin/change-password', data);
export const getAdminStats = () => request.get('/admin/stats');
export const getRepaymentStats = (params) => request.get('/admin/repayment-stats', { params });
export const getProjectCashInsights = () => request.get('/admin/project-cash-insights');
export const getAdminAuditLogs = (params) => request.get('/admin/audit-logs', { params });
export const exportAdminAuditLogs = (params) => request.get('/admin/audit-logs/export', { params, responseType: 'blob' });
export const getKycReviewQueue = (params) => request.get('/admin/kyc-review-queue', { params });
export const reviewKycUser = (id, data) => request.post(`/admin/kyc-review/user/${id}`, data);
export const batchReviewKyc = (data) => request.post('/admin/kyc-review/batch', data);
export const getMonitoringSummary = () => request.get('/admin/monitoring-summary');
export const getMessageCenter = (params) => request.get('/admin/message-center', { params });
export const getMessageTemplates = () => request.get('/admin/message-templates');
export const saveMessageTemplate = (data) => request.post('/admin/message-templates', data);
export const toggleMessageTemplate = (id, data) => request.patch(`/admin/message-templates/${id}/active`, data);
export const getMonitoringDrilldown = (metric) => request.get(`/admin/monitoring/drilldown/${metric}`);
export const getRiskDecisions = (params) => request.get('/admin/risk-decisions', { params });
export const getRiskSignals = (params) => request.get('/admin/risk-signals', { params });
export const overrideRiskDecision = (decisionId, data) => request.post(`/admin/risk-decisions/${decisionId}/override`, data);
export const ingestRiskSignal = (data) => request.post('/admin/risk-signals', data);
export const getRiskPolicies = (params) => request.get('/admin/risk-policies', { params });
export const getRiskPolicyHistory = (policyKey) => request.get(`/admin/risk-policies/${policyKey}/history`);
export const createRiskPolicy = (data) => request.post('/admin/risk-policies', data);
export const updateRiskPolicy = (id, data) => request.patch(`/admin/risk-policies/${id}`, data);
export const copyRiskPolicy = (id) => request.post(`/admin/risk-policies/${id}/copy`);
export const activateRiskPolicy = (id) => request.post(`/admin/risk-policies/${id}/activate`);
export const disableRiskPolicy = (id) => request.post(`/admin/risk-policies/${id}/disable`);
export const getFinanceReconciliation = (params) => request.get('/admin/finance/reconciliation', { params });
export const getAdminLoginHistory = (id, params) => request.get(`/admin/admin-users/${id}/login-history`, { params });
export const getConfigHistory = (type, id) => request.get(`/admin/config-history/${type}/${id}`);
export const copyChannel = (id) => request.post(`/admin/channels/${id}/copy`);
export const copyProduct = (id) => request.post(`/admin/products/${id}/copy`);
export const sendAdminReminder = (id, data) => request.post(`/admin/loans/${id}/remind`, data);
export const getChannels = (params) => request.get('/admin/channels', { params });
export const getExclusiveLinks = () => request.get('/admin/exclusive-links');
export const createChannel = (data) => request.post('/admin/channels', data);
export const updateChannel = (id, data) => request.patch(`/admin/channels/${id}`, data);
export const getProducts = (params) => request.get('/admin/products', { params });
export const createProduct = (data) => request.post('/admin/products', data);
export const updateProduct = (id, data) => request.patch(`/admin/products/${id}`, data);
export const getActiveComplianceRule = () => request.get('/admin/compliance-rules/active');
export const createComplianceRule = (data) => request.post('/admin/compliance-rules', data);
export const getMomoTransactions = (params) => request.get('/admin/momo-transactions', { params });
export const getDisbursementFailures = (params) => request.get('/admin/disbursement-failures', { params });
export const uploadProductRightsImage = (formData) => request.post('/admin/products/rights-image', formData);
export const getEcardPool = (params) => request.get('/admin/ecard-pool', { params });
export const createEcardPoolItem = (data) => request.post('/admin/ecard-pool', data);
export const updateEcardPoolItem = (id, data) => request.patch(`/admin/ecard-pool/${id}`, data);
export const uploadEcardPoolExcel = (formData) => request.post('/admin/ecard-pool/batch-upload', formData);
export const downloadEcardPoolTemplate = () => request.get('/admin/ecard-pool/template', { responseType: 'blob' });
export const getAdminUsers = (params) => request.get('/admin/admin-users', { params });
export const getBusinessAdvisors = (params) => request.get('/admin/admin-users/business-advisors', { params });
export const createAdminUser = (data) => request.post('/admin/admin-users', data);
export const updateAdminUser = (id, data) => request.patch(`/admin/admin-users/${id}`, data);
export const deleteAdminUser = (id) => request.delete(`/admin/admin-users/${id}`);

// User API for Admin
export const getUsers = (params) => request.get('/admin/users', { params });
export const getUserSourceChannels = (params) => request.get('/admin/users/source-channels', { params });
export const getUserDetail = (id) => request.get(`/admin/users/${id}`);
export const getUserIpAudit = (id) => request.get(`/admin/users/${id}/ip-audit`);
export const createFrontUser = (data) => request.post('/admin/users', data);
export const resetFrontUserPassword = (id, data) => request.post(`/admin/users/${id}/reset-password`, data);
export const unlockUserLocationRisk = (id) => request.post(`/admin/users/${id}/location-risk/unlock`);
export const getRiskReportByUser = (data) => request.post('/admin/risk/report', data);
export const getCompositeRiskReportByUser = (data) => request.post('/admin/risk/composite-report', data);
export const querySingleRiskReport = (data) => request.post('/admin/risk/single-report', data);
export const getSingleRiskReportHistory = (params) => request.get('/admin/risk/single-reports', { params });
export const getSingleRiskReportDetail = (id) => request.get(`/admin/risk/single-reports/${id}`);
export const getBlacklist = (params) => request.get('/admin/blacklist', { params });
export const uploadBlacklist = (formData) => request.post('/admin/blacklist/upload', formData);
export const blacklistUser = (id, data) => request.post(`/admin/users/${id}/blacklist`, data);
export const removeBlacklistUser = (id, data) => request.post(`/admin/users/${id}/blacklist/remove`, data);
export const getOverdueFeeConfigs = (params) => request.get('/admin/overdue-fee-configs', { params });
export const createOverdueFeeConfig = (data) => request.post('/admin/overdue-fee-configs', data);

// Loan API for Admin
export const getLoans = (params) => request.get('/admin/loans', { params });
export const getLoanLedger = (id) => request.get(`/admin/loans/${id}/ledger`);
export const getLoanPurchaseContract = (id) => request.get(`/admin/loans/${id}/purchase-contract`);
export const getLoanMomoMandate = (id) => request.get(`/admin/loans/${id}/momo-mandate`);
export const reviewLoan = (id, data) => request.post(`/admin/loans/${id}/review`, data);
export const updateLoan = (id, data) => request.patch(`/admin/loans/${id}`, data);
export const disburseLoan = (id, data) => request.post(`/admin/loans/${id}/disburse`, data);
export const rejectCardLoan = (id, data) => request.post(`/admin/loans/${id}/reject-card`, data);
export const reissueCardLoan = (id) => request.post(`/admin/loans/${id}/reissue-card`);
export const closeCardReissue = (id) => request.post(`/admin/loans/${id}/close-card-reissue`);
export const extendLoan = (id, data) => request.post(`/admin/loans/${id}/extend`, data);
export const adjustAvailableCredit = (id, data) => request.post(`/admin/loans/${id}/available-credit/adjust`, data);
export const setApprovedCreditLimit = (id, data) => request.post(`/admin/loans/${id}/approved-credit/set`, data);
export const updateOverdueDisplay = (id, data) => request.post(`/admin/loans/${id}/overdue-display`, data);
export const settleLoan = (id) => request.post(`/admin/loans/${id}/settle`);
export const remindLoan = (id, data) => request.post(`/admin/loans/${id}/remind`, data);
export const collectLoan = (id, data) => request.post(`/admin/loans/${id}/collect`, data);
export const financeReconcileLoan = (id, data) => request.post(`/admin/loans/${id}/finance-reconcile`, data);
export const ackRepayAttempt = (id) => request.post(`/admin/loans/${id}/ack-repay-attempt`);
export const getLoanAssignees = (params) => request.get('/admin/loan-assignees', { params });
export const assignLoan = (id, data) => request.post(`/admin/loans/${id}/assign`, data);
